### PR TITLE
Updated buildenv

### PR DESCRIPTION
**Pull request by cpkr162**

### CODE REVIEW

**Comment by v1gnesh** [comment]
Shouldn't we try to fix 3.9.6? It'll show up in an automated PR soon anyway.

**Comment by IgorTodorovskiIBM** [comment]
Curious, what was the issue with 3.9.6?

**Comment by cpkr162** [comment]
in high-level, I could see some changes has made to the list of linux libraries and config files in > 3.8.1 version and trying to understand it what causing the issue for below one.

org.codehaus.plexus.classworlds.launcher.ConfigurationException: Unhandled configuration (1): ????@??@???K??????K?????K???K??????@????@??????K????
	at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.parse(ConfigurationParser.java:309)
	at org.codehaus.plexus.classworlds.launcher.Configurator.configure(Configurator.java:131)
	at org.codehaus.plexus.classworlds.launcher.Launcher.configure(Launcher.java:128)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:401)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)

**Comment by cpkr162** [comment]
@IgorTodorovskiIBM  @v1gnesh Maven will run with Java 8 till <= 3.9.1 version. it's good to have one build to support java 8 applications

**Comment by IgorTodorovskiIBM** [comment]
> @IgorTodorovskiIBM @v1gnesh Maven will run with Java 8 till <= 3.9.1 version. it's good to have one build to support java 8 applications

One way to support 3.9.6 or later is to get this release out the door and then bump up the version.

With zopen you can install older release. `zopen install maven@3.9.1` or `zopen install maven --select` for example

**Review by IgorTodorovskiIBM — APPROVED** [review]
LGTM

**Pull request merged**
